---
- name: combine configs
  assemble:
    src: "{{ clojure_uberjar_webapp_app_config_dir }}"
    dest: "{{ clojure_uberjar_webapp_app_combined_config_path }}"
    delimiter: "\n"

- name: restart web app
  service: name={{ clojure_uberjar_webapp_app_service_name }} state=restarted
  become: yes
  become_method: sudo
  tags:
    - deploy